name: On PR or push to main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.0
          run_install: true

      - name: NX build - core,tree,multi-backend
        run: pnpm run nx -- run-many --target=build --projects=core,tree,sortable
        working-directory: .
